export const PRODUCTS = [
	{
		id: 1,
		product_name: "Rayes Alpha",
		description: "Hands-free, Hands-on Musch experience",
		trader: "Musch",
		price: 350,
		currency: "$",
		thumb: "src/assets/stoles/1.png",
	},
	{
		id: 2,
		product_name: "Rayes X30",
		description: "Hands-free, Hands-on Musch experience",
		trader: "Musch",
		price: 350,
		currency: "$",
		thumb: "src/assets/stoles/2.png",
	},
	{
		id: 3,
		product_name: "Ra Alpha",
		description: "Hands-on Musch experience",
		price: 350,
		trader: "Musch",
		currency: "$",
		thumb: "src/assets/stoles/3.png",
	},
	{
		id: 4,
		product_name: "Rayes Alpha",
		description: "Hands-free, Hands-on Musch experience",
		price: 350,
		trader: "Musch",
		currency: "$",
		thumb: "src/assets/stoles/1.png",
	},
	{
		id: 5,
		product_name: "Rayes Alpha",
		description: "Hands-free, Hands-on Musch experience",
		price: 350,
		trader: "Musch",
		currency: "$",
		thumb: "src/assets/stoles/1.png",
	},
	{
		id: 6,
		product_name: "Rayes X30",
		description: "Hands-free, Hands-on Musch experience",
		price: 350,
		trader: "Musch",
		currency: "$",
		thumb: "src/assets/stoles/2.png",
	},
	{
		id: 7,
		product_name: "Ra Alpha",
		description: "Hands-on Musch experience",
		price: 350,
		trader: "Musch",
		currency: "$",
		thumb: "src/assets/stoles/3.png",
	},
	{
		id: 8,
		product_name: "Rayes Alpha",
		description: "Hands-free, Hands-on Musch experience",
		price: 350,
		trader: "Musch",
		currency: "$",
		thumb: "src/assets/stoles/1.png",
	},
	{
		id: 9,
		product_name: "Rayes Alpha",
		description: "Hands-free, Hands-on Musch experience",
		price: 350,
		trader: "Musch",
		currency: "$",
		thumb: "src/assets/stoles/1.png",
	},
];
