/* The code snippet is exporting a constant variable named `PRODUCTS`. This variable is an array of
objects, where each object represents a product. Each product object has properties such as `id`,
`product_name`, `description`, `trader`, `price`, `currency`, and `thumb`. These properties provide
information about each product, such as its unique identifier, name, description, trader, price,
currency, and thumbnail image source. */
export const PRODUCTS = [
	{
		id: 1,
		product_name: "Rayes Alpha",
		description: "Hands-free, Hands-on Musch experience",
		trader: "Kofi Dee",
		price: 350,
		currency: "$",
		thumb: "src/assets/stoles/1.png",
	},
	{
		id: 2,
		product_name: "Rayes X30",
		description: "Hands-free, Hands-on Musch experience",
		trader: "Ama Yeboah",
		price: 350,
		currency: "$",
		thumb: "src/assets/stoles/2.png",
	},
	{
		id: 3,
		product_name: "Ra Alpha",
		description: "Hands-on Musch experience",
		price: 350,
		trader: "Yaa Boamah",
		currency: "$",
		thumb: "src/assets/stoles/3.png",
	},
	{
		id: 4,
		product_name: "Rayes Alpha",
		description: "Hands-free, Hands-on Musch experience",
		price: 350,
		trader: "Aba Mensah",
		currency: "$",
		thumb: "src/assets/stoles/1.png",
	},
	{
		id: 5,
		product_name: "Rayes Alpha",
		description: "Hands-free, Hands-on Musch experience",
		price: 350,
		trader: "Kwame Alfred",
		currency: "$",
		thumb: "src/assets/stoles/1.png",
	},
	{
		id: 6,
		product_name: "Rayes X30",
		description: "Hands-free, Hands-on Musch experience",
		price: 350,
		trader: "Josh Appiah",
		currency: "$",
		thumb: "src/assets/stoles/2.png",
	},
	{
		id: 7,
		product_name: "Ra Alpha",
		description: "Hands-on Musch experience",
		price: 350,
		trader: "Jackie Ntow",
		currency: "$",
		thumb: "src/assets/stoles/3.png",
	},
	{
		id: 8,
		product_name: "Rayes Alpha",
		description: "Hands-free, Hands-on Musch experience",
		price: 350,
		trader: "Rita Sereboo",
		currency: "$",
		thumb: "src/assets/stoles/1.png",
	},
	{
		id: 9,
		product_name: "Rayes Alpha",
		description: "Hands-free, Hands-on Musch experience",
		price: 350,
		trader: "Mahama Aminu",
		currency: "$",
		thumb: "src/assets/stoles/1.png",
	},
];
