// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEZXgSEUHRakI47DsbNLc4Gye9CuZ7wH0',
    appId: '1:569930545737:web:b97290aea98679675a5d98',
    messagingSenderId: '569930545737',
    projectId: 'capstonetest-cf4da',
    authDomain: 'capstonetest-cf4da.firebaseapp.com',
    storageBucket: 'capstonetest-cf4da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4D85pULOFpFP1-RlaOhi-J-oG-rzjrEw',
    appId: '1:569930545737:android:63d924806f86adab5a5d98',
    messagingSenderId: '569930545737',
    projectId: 'capstonetest-cf4da',
    storageBucket: 'capstonetest-cf4da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw_EUKJfddWYnOTz3DsL_cIB3OeFyAS_s',
    appId: '1:569930545737:ios:c534e92d852b6a905a5d98',
    messagingSenderId: '569930545737',
    projectId: 'capstonetest-cf4da',
    storageBucket: 'capstonetest-cf4da.appspot.com',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw_EUKJfddWYnOTz3DsL_cIB3OeFyAS_s',
    appId: '1:569930545737:ios:94e9a0f139c3e4ae5a5d98',
    messagingSenderId: '569930545737',
    projectId: 'capstonetest-cf4da',
    storageBucket: 'capstonetest-cf4da.appspot.com',
    iosBundleId: 'com.example.capstone.RunnerTests',
  );
}
